global:
  scrape_interval:     15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: spring-actuator
  metrics_path: '/actuator/prometheus'
  static_configs:
    - targets: ['localhost:9090']
