/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BeanDI;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class App {

    public static void main(String[] args) {

        final ConfigurableApplicationContext context = SpringApplication.run(App.class, args);

        AppProcess appProcess = context.getBean(AppConfiguration.class).getAppProcess();
        appProcess.run();
        context.close();
    }

}
