version: '3'

services:
  application:
    image: application:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/application
    ports:
      - "8080:8080"
  #    depends_on:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: company
    ports:
      - "5432:5432"

#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 8080:8080