/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {


    public static void main(String[] args) throws SQLException, ClassNotFoundException  {

        Class.forName("org.postgresql.Driver");

        // установить соединение
        Connection connection = DriverManager
            .getConnection("jdbc:postgresql://localhost:5432/main", "postgres", "postgres");

        StatementOperation stmtop = new StatementOperation();
        stmtop.fun(connection);


    }
}
